### ISSUE TITLE
Issue, Items duping on respawn and not changing gamemode back

### ISSUE THREAD

**Issue by FancyBelt798245** [blueysh/Ghoster#1]
Hey man just letting you know I did a little testing with this plugin on my 1.20.1 PurPur Minecraft server and I've found a few issues, first of all when you die and the countdown is over you don't get changed back into survival mode also you don't get spawned at spawn.

**Comment by jansanti** [comment]
Hi, thanks for letting me know! The plug-in wasn't tested directly on a Purpur server so I will have to look into it. Can you go into more detail about what happens and how I could replicate the bug to fix it? Thank you!

**Comment by jansanti** [comment]
Looking into your description so far, testing on Purpur 1.20.1 the plugin works as normal. Are you using any plugins on your server that might change or interfere with the plugin's behavior?

**Comment by FancyBelt798245** [comment]
I think it would have to do with one of the plugins I’m using probably CMI

**Comment by jansanti** [comment]
Yes, that plugin has a lot of features so you might want to look into which ones might be conflicting with Ghoster. If you find any other bugs please let me know!
